apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: tfg
  name: hello-v1
  namespace: default
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    role: hello-v1
