apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v1
  labels:
    app.kubernetes.io/instance: tfg
spec:
  replicas: 3
  selector:
    matchLabels:
      role: hello-v1
  template:
    metadata:
      labels:
        role: hello-v1
    spec:
      containers:
      - name: hello-v1
        image: ghcr.io/opadial203/tfg:64
        ports:
        - containerPort: 80


